Vagrant.configure("2") do |config|
  # Ubuntu 22.04
  config.vm.box = "ubuntu/jammy64"

  # VM settings
  config.vm.hostname = "k8s-minikube"
  config.vm.network "private_network", type: "dhcp"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 2
  end

  # Run external script
  config.vm.provision "shell", path: "install-dependencies.sh"
end
